# .streamlit/secrets.toml
[connections.gsheets]
OPENAI_API_KEY="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"
spreadsheet = "https://docs.google.com/spreadsheets/d/1okyCzz15cThwRYOePRBynKZoIjuclzVdGy8nCJYpbFI/edit?pli=1&gid=0#gid=0"
